### ISSUE TITLE
Bug : C4Log.setLevel(java.lang.String, int) C4Log.setLevel(Native Method)

### ISSUE THREAD

**Issue by praveen-kanwar** [couchbase/couchbase-lite-android-ce#24]
java.lang.UnsatisfiedLinkError: No implementation found for void com.couchbase.lite.internal.core.C4Log.setLevel(java.lang.String, int) (tried Java_com_couchbase_lite_internal_core_C4Log_setLevel and Java_com_couchbase_lite_internal_core_C4Log_setLevel__Ljava_lang_String_2I)
        at com.couchbase.lite.internal.core.C4Log.setLevel(Native Method)
        at com.couchbase.lite.FileLogger.setupDomainObjects(FileLogger.java:84)
        at com.couchbase.lite.FileLogger.<init>(FileLogger.java:47)
        at com.couchbase.lite.Log.<init>(Log.java:35)
        at com.couchbase.lite.AbstractDatabase.<clinit>(AbstractDatabase.java:77)

**Comment by bmeike** [comment]
We need a little more information here.  What version of CBL are you using?  Where did you get it?

The method is defined here:
https://github.com/couchbase/couchbase-lite-java/blob/4f9166f99e9fcc0931a12841a37acbe988d81b40/src/shared/main/cpp/native_c4.cc#L96

**Comment by bmeike** [comment]
Please feel absolutely free to re-open this, if you have more information...
