### ISSUE TITLE
Reading query content from allResults() crash

### ISSUE THREAD

**Issue by bpolanec** [couchbase/couchbase-lite-android-ce#30]
I've built from sources library and using couchbase-lite-android-2.7.0-SNAPSHOT-release.aar
couchbase-android-ce HEAD at commit: e066b37
couchbase-android-core HEAD at commit: https://github.com/couchbase/couchbase-lite-core/commit/2290bce442cca4de12ca95e7dc3c83d6ab19d0e9

Crash when trying to read allResults() from ResultSet with following content:
> Runtime aborting...
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:508] 
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]     string: '{QueryEnum#1199} --> ["mainUser110666__fpm__MFRHGZLOMNSXG000",{"accessType":"all","appId":"fpm","bigData":false,"columns":[{"field":"absence_matchcode","hidden":false,"id":"absence_matchcode","name":"absence_matchcode","nameI18n":{"de":"Matchcode","en":"matchcode","es":"código de asociación","fr":"Matchcode"},"required":"ALL","settings":{"notEditable":false,"auxiliaryColumns":null,"dataType":"text","dependsOnColumns":null,"fixValue":false,"reference":{"category":"mainUser110666__fpm__MVWXA3DPPFSWK4Y0","item":"employee_matchcode"},"filterOnParentSelection":true},"unique":false,"uniqueKeys":[],"visibility":"visible","dataTypeDefinitionId":"pointer"},{"field":"absence_typeOfAbsence","hidden":false,"id":"absence_typeOfAbsence","name":"absence_typeOfAbsence","nameI18n":{"de":"Buchungstext","en":"type of absence","es":"tipo de ausencia","fr":"Type d'absence"},"required":"ALL","settings":{"notEditable":false,"auxiliaryColu
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]     input: '0x7b 0x51 0x75 0x65 0x72 0x79 0x45 0x6e 0x75 0x6d 0x23 0x31 0x31 0x39 0x39 0x7d 0x20 0x2d 0x2d 0x3e 0x20 0x5b 0x22 0x6d 0x61 0x69 0x6e 0x55 0x73 0x65 0x72 0x31 0x31 0x30 0x36 0x36 0x36 0x5f 0x5f 0x66 0x61 0x69 0x72 0x70 0x61 0x72 0x6b 0x65 0x6e 0x50 0x61 0x72 0x6b 0x69 0x6e 0x67 0x4d 0x61 0x6e 0x61 0x67 0x65 0x72 0x5f 0x5f 0x4d 0x46 0x52 0x48 0x47 0x5a 0x4c 0x4f 0x4d 0x4e 0x53 0x58 0x47 0x30 0x30 0x30 0x22 0x2c 0x7b 0x22 0x61 0x63 0x63 0x65 0x73 0x73 0x54 0x79 0x70 0x65 0x22 0x3a 0x22 0x61 0x6c 0x6c 0x22 0x2c 0x22 0x61 0x70 0x70 0x49 0x64 0x22 0x3a 0x22 0x66 0x61 0x69 0x72 0x70 0x61 0x72 0x6b 0x65 0x6e 0x50 0x61 0x72 0x6b 0x69 0x6e 0x67 0x4d 0x61 0x6e 0x61 0x67 0x65 0x72 0x22 0x2c 0x22 0x62 0x69 0x67 0x44 0x61 0x74 0x61 0x22 0x3a 0x66 0x61 0x6c 0x73 0x65 0x2c 0x22 0x63 0x6f 0x6c 0x75 0x6d 0x6e 0x73 0x22 0x3a 0x5b 0x7b 0x22 0x66 0x69 0x65 0x6c 0x64 0x22 0x3a 0x22 0x61 0x62 0x73 0x65 0x6e 0x63 0x65 0x5f 0x6d 0x61 0x74 0x63 0x68 0x63 0x6f 0x64 0x65 0x22 0x2c 0x22 0x68 0x69 0x64 0x64 
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]     in call to NewStringUTF
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]     from boolean com.couchbase.lite.internal.core.C4QueryEnumerator.next(long)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516] "main" prio=5 tid=1 Runnable
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x74743518 self=0x7f1ecc0a00
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   | sysTid=1605 nice=-10 cgrp=default sched=0/0 handle=0x7f23ddb9c8
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   | state=R schedstat=( 62082792324 4022667086 38727 ) utm=5251 stm=957 core=5 HZ=100
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   | stack=0x7ff720a000-0x7ff720c000 stackSize=8MB
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   | held mutexes= "mutator lock"(shared held)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #00 pc 0000000000397614  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #01 pc 000000000045dde8  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+348)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #02 pc 00000000002d59e0  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1040)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #03 pc 00000000002d5e60  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #04 pc 0000000000108ab0  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+148)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #05 pc 0000000000108f7c  /system/lib64/libart.so (_ZN3art11ScopedCheck14CheckUtfStringEPKcb+732)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #06 pc 0000000000106a78  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+856)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #07 pc 00000000000fd23c  /system/lib64/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+648)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #08 pc 0000000000179514  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (???)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #09 pc 000000000024d5d4  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (_ZN8litecore9LogDomain4vlogENS_8LogLevelEjbPKcSt9__va_list+408)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #10 pc 000000000024e17c  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (_ZNK8litecore7Logging5_logvENS_8LogLevelEPKcSt9__va_list+272)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #11 pc 000000000024e048  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (_ZNK8litecore7Logging4_logENS_8LogLevelEPKcz+108)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #12 pc 0000000000259b64  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (_ZN8litecore21SQLiteQueryEnumerator4nextEv+244)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #13 pc 000000000018d270  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (_ZN21C4QueryEnumeratorImpl4nextEv+28)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #14 pc 000000000018d21c  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (???)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #15 pc 0000000000186b08  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (_ZN10c4Internal8tryCatchIbEET_P7C4ErrorN6fleece12function_refIFS1_vEEE+20)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #16 pc 000000000018ba1c  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (c4queryenum_next+52)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #17 pc 000000000017d0e8  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/lib/arm64/libLiteCoreJNI.so (Java_com_couchbase_lite_internal_core_C4QueryEnumerator_next+40)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   native: #18 pc 0000000000006fd8  /data/app/com.myProject -vSPixWGaX7dtpPkmnm3Lzg==/oat/arm64/base.odex (Java_com_couchbase_lite_internal_core_C4QueryEnumerator_next__J+152)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   at com.couchbase.lite.internal.core.C4QueryEnumerator.next(Native method)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   at com.couchbase.lite.internal.core.C4QueryEnumerator.next(C4QueryEnumerator.java:73)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   at com.couchbase.lite.ResultSet.next(ResultSet.java:91)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   - locked <0x0f066af4> (a java.lang.Object)
> 2019-10-02 15:01:29.881 1605-1605/com.myProject A/zygote64: runtime.cc:516]   at com.couchbase.lite.ResultSet.allResults(ResultSet.java:117

**Comment by bmeike** [comment]
Ugg.  I thought we'd nailed the last of those UTF-8 issues.

Can you give me the commit for couchbase-lite-android?

**Comment by bmeike** [comment]
I suspect that this will not fix the issue, but would you please do the following:  ```
cd $CBL_ANDROID_CE
git submodule update --remote
cd couchbase-lite-core
git submodule update --recursive
```
Note the two different flags on the submodule updates...

**Comment by bpolanec** [comment]
Tried with:
f477ad9 ce
couchbase/couchbase-lite-core@46d5ab73 core

still error. 

Pasting the new stack:
>2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]     string: '{QueryEnum#1140} --> ["mainUser110666__fairparkenParkingManager__MFRHGZLOMNSXG000",{"accessType":"all","appId":"fairparkenParkingManager","bigData":false,"columns":[{"field":"absence_matchcode","hidden":false,"id":"absence_matchcode","name":"absence_matchcode","nameI18n":{"de":"Matchcode","en":"matchcode","es":"código de asociación","fr":"Matchcode"},"required":"ALL","settings":{"notEditable":false,"auxiliaryColumns":null,"dataType":"text","dependsOnColumns":null,"fixValue":false,"reference":{"category":"mainUser110666__fairparkenParkingManager__MVWXA3DPPFSWK4Y0","item":"employee_matchcode"},"filterOnParentSelection":true},"unique":false,"uniqueKeys":[],"visibility":"visible","dataTypeDefinitionId":"pointer"},{"field":"absence_typeOfAbsence","hidden":false,"id":"absence_typeOfAbsence","name":"absence_typeOfAbsence","nameI18n":{"de":"Buchungstext","en":"type of absence","es":"tipo de ausencia","fr":"Type d'absence"},"required":"ALL","settings":{"notEditable":false,"auxiliary
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]     input: '0x7b 0x51 0x75 0x65 0x72 0x79 0x45 0x6e 0x75 0x6d 0x23 0x31 0x31 0x34 0x30 0x7d 0x20 0x2d 0x2d 0x3e 0x20 0x5b 0x22 0x6d 0x61 0x69 0x6e 0x55 0x73 0x65 0x72 0x31 0x31 0x30 0x36 0x36 0x36 0x5f 0x5f 0x66 0x61 0x69 0x72 0x70 0x61 0x72 0x6b 0x65 0x6e 0x50 0x61 0x72 0x6b 0x69 0x6e 0x67 0x4d 0x61 0x6e 0x61 0x67 0x65 0x72 0x5f 0x5f 0x4d 0x46 0x52 0x48 0x47 0x5a 0x4c 0x4f 0x4d 0x4e 0x53 0x58 0x47 0x30 0x30 0x30 0x22 0x2c 0x7b 0x22 0x61 0x63 0x63 0x65 0x73 0x73 0x54 0x79 0x70 0x65 0x22 0x3a 0x22 0x61 0x6c 0x6c 0x22 0x2c 0x22 0x61 0x70 0x70 0x49 0x64 0x22 0x3a 0x22 0x66 0x61 0x69 0x72 0x70 0x61 0x72 0x6b 0x65 0x6e 0x50 0x61 0x72 0x6b 0x69 0x6e 0x67 0x4d 0x61 0x6e 0x61 0x67 0x65 0x72 0x22 0x2c 0x22 0x62 0x69 0x67 0x44 0x61 0x74 0x61 0x22 0x3a 0x66 0x61 0x6c 0x73 0x65 0x2c 0x22 0x63 0x6f 0x6c 0x75 0x6d 0x6e 0x73 0x22 0x3a 0x5b 0x7b 0x22 0x66 0x69 0x65 0x6c 0x64 0x22 0x3a 0x22 0x61 0x62 0x73 0x65 0x6e 0x63 0x65 0x5f 0x6d 0x61 0x74 0x63 0x68 0x63 0x6f 0x64 0x65 0x22 0x2c 0x22 0x68 0x69 0x64 0
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]     in call to NewStringUTF
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]     from boolean com.couchbase.lite.internal.core.C4QueryEnumerator.next(long)
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504] "main" prio=5 tid=1 Runnable
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x74743518 self=0x7f1ecc0a00
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   | sysTid=22524 nice=-10 cgrp=default sched=0/0 handle=0x7f23ddb9c8
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   | state=R schedstat=( 43513491470 3255494434 27260 ) utm=3717 stm=634 core=4 HZ=100
2019-10-08 11:52:02.401 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   | stack=0x7ff720a000-0x7ff720c000 stackSize=8MB
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   | held mutexes= "mutator lock"(shared held)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #00 pc 0000000000397614  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #01 pc 000000000045dde8  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+348)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #02 pc 00000000002d59e0  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1040)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #03 pc 00000000002d5e60  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #04 pc 0000000000108ab0  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+148)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #05 pc 0000000000108f7c  /system/lib64/libart.so (_ZN3art11ScopedCheck14CheckUtfStringEPKcb+732)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #06 pc 0000000000106a78  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+856)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #07 pc 00000000000fd23c  /system/lib64/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+648)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #08 pc 0000000000179724  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (???)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #09 pc 000000000024fa28  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (_ZN8litecore9LogDomain4vlogENS_8LogLevelEjbPKcSt9__va_list+408)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #10 pc 00000000002505d0  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (_ZNK8litecore7Logging5_logvENS_8LogLevelEPKcSt9__va_list+272)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #11 pc 000000000025049c  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (_ZNK8litecore7Logging4_logENS_8LogLevelEPKcz+108)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #12 pc 000000000025c09c  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (_ZN8litecore21SQLiteQueryEnumerator4nextEv+244)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #13 pc 000000000018e480  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (_ZN21C4QueryEnumeratorImpl4nextEv+28)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #14 pc 000000000018e42c  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (???)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #15 pc 0000000000186d18  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (_ZN10c4Internal8tryCatchIbEET_P7C4ErrorN6fleece12function_refIFS1_vEEE+20)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #16 pc 000000000018cc2c  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (c4queryenum_next+52)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #17 pc 000000000017d2f8  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/lib/arm64/libLiteCoreJNI.so (Java_com_couchbase_lite_internal_core_C4QueryEnumerator_next+40)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   native: #18 pc 0000000000006fd8  /data/app/com.myProjectr-DEigdqS_4Dbb15lziShVnQ==/oat/arm64/base.odex (Java_com_couchbase_lite_internal_core_C4QueryEnumerator_next__J+152)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   at com.couchbase.lite.internal.core.C4QueryEnumerator.next(Native method)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   at com.couchbase.lite.internal.core.C4QueryEnumerator.next(C4QueryEnumerator.java:73)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   at com.couchbase.lite.ResultSet.next(ResultSet.java:91)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   - locked <0x051fe589> (a java.lang.Object)
2019-10-08 11:52:02.402 22524-22524/com.myProjectr A/zygote64: java_vm_ext.cc:504]   at com.couchbase.lite.ResultSet.allResults(ResultSet.java:117)

**Comment by bmeike** [comment]
@bpolanec Can you give me the commit hash for couchbase-lite-android (first layer down).  Thanks.

**Comment by bpolanec** [comment]
https://github.com/couchbase/couchbase-lite-android/commit/6f84962147dc485c1926bdacfd43c2e83e14a9fa

**Comment by bmeike** [comment]
Thanks!

**Comment by bmeike** [comment]
This is a bug.  We are attempting to log the JSON.  Apparently it was imported from an non-Java platform, is not Modified UTF-8, and causes the crash.  Filing CBL-463 to track this.

**Comment by bpolanec** [comment]
Thanks for the info.

**Comment by bmeike** [comment]
Fixed in 2.7.0
